### ISSUE TITLE
homebrew installing update

### ISSUE THREAD

**Issue by jmsundar** [minio/homebrew-stable#19]
I get the following warning when attempting to `brew info` or `brew update` minio/stable/minio. The formula installs successfully, but the `brew services` information isn't shown.

```
brew info minio/stable/minio 
minio/stable/minio: stable 20180118203321Z
Amazon S3 compatible object storage server
https://github.com/minio/minio
/usr/local/Cellar/minio/20180102230700Z_1 (4 files, 25.0MB)
  Built from source on 2018-01-04 at 10:39:58
/usr/local/Cellar/minio/20180118203321Z_1 (3 files, 25.0MB) *
  Built from source on 2018-02-05 at 12:28:47
From: https://github.com/minio/homebrew-stable/blob/master/minio.rb
==> Requirements
Required: arch ✔
Error: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/minio/homebrew-stable/minio.rb:64:in `plist'
Please report this to the minio/stable tap!
Or, even better, submit a PR to fix it!
```

```
brew -v upgrade minio/stable/minio 
==> Upgrading 1 outdated package, with result:
minio/stable/minio 20180118203321Z_1
==> Upgrading minio/stable/minio 
rm /usr/local/bin/minio
/usr/bin/sandbox-exec -f /tmp/homebrew20180205-24536-1myk9yt.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/minio/homebrew-stable/minio.rb --verbose
==> Downloading https://dl.minio.io/server/minio/release/darwin-amd64/minio.RELEASE.2018-01-18T20-33-21Z
/usr/bin/curl --show-error --user-agent Homebrew/1.5.2-40-ga44b21b (Macintosh; Intel Mac OS X 10.13.2) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/jayu/Library/Caches/Homebrew/minio-20180118203321Z.2018-01-18T20-33-21Z.incomplete https://dl.minio.io/server/minio/release/darwin-amd64/minio.RELEASE.2018-01-18T20-33-21Z
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.9M  100 24.9M    0     0  1082k      0  0:00:23  0:00:23 --:--:-- 1246k
==> Verifying minio-20180118203321Z.2018-01-18T20-33-21Z checksum
==> Cleaning
==> Finishing up
Error: Failed to install plist file
ln -s ../Cellar/minio/20180118203321Z_1/bin/minio minio
/usr/bin/sandbox-exec -f /tmp/homebrew20180205-25080-wmb3l3.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/minio/homebrew-stable/minio.rb -v
Error: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/minio/homebrew-stable/minio.rb:64:in `plist'
Please report this to the minio/stable tap!
Or, even better, submit a PR to fix it!
```

**Comment by harshavardhana** [comment]
we will fix it soon @jmsundar thanks for the report.
